linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec
    - prealloc
    - gocritic
    - bodyclose
    - gocyclo
    - dupl
    - funlen
    - gocognit
    - goconst
    - godox
    - maligned
    - depguard
    - dogsled
    - whitespace

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 20

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
        - gocognit
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
  skip-files:
    - ".*_test\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 